Update index.html
Ishika11/SoftwareProductSprint_portfolio pull request #3
Opened 2020-07-08 10:26 UTC by Ishika11

2020-07-08 15:30 UTC, abhatia2107 requested changes

2020-07-08 15:30 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/images2.html
> +</html>
nit: Add a newline. Always a good idea to have an empty newline at end of file.
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2020-07-08 15:30 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/images2.html
> +<!DOCTYPE html>
Just edit the same file. Keep the same name i.e. images.html

2020-07-08 15:30 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/random.html
> +      <img src="images2/mypic.jpg"/>
When you change filename to images, don't forget to update path here.

2020-07-08 15:30 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/random.html
> +
Add title back. You can change text in title but should have a title.

2020-07-08 15:35 UTC, abhatia2107 commented
Would also request you to make some css changes as part of this PR. Try playing around different styles.

2020-07-08 20:24 UTC, Ishika11 commented
> Add title back. You can change text in title but should have a title.

2020-07-10 09:00 UTC, abhatia2107 requested changes

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/images.html
> +</html>
newline

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/mybook.html
> +</html>
newline

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/mybook.html
> +      <h1 style="color: Orange;">Helix - Ishika Kumar</h1>
Avoid inline style

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/mybook.html
> +        <a href="images/Helix.jpg"><img src="images/Helix.jpg"/></a>
add alt text

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/style_index.css
> +{
be consistent with placement of {
Either put it in newline or at end of last line. Fine with anything but would appreciate consistency.

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/style_random.css
> +}
newline

2020-07-10 09:00 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/style_my_book.css
> +}
newline

2020-07-11 19:24 UTC, closed without merging