Added/ changed necessary things
Ishika11/SoftwareProductSprint_portfolio pull request #4
Opened 2020-07-08 21:13 UTC by Ishika11

2020-07-09 09:16 UTC, abhatia2107 requested changes

2020-07-09 09:16 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/index.html
> +      <h1 style="color: yellow">Ishika (^_^)</h1>
Remove inline css.

2020-07-09 12:29 UTC, Ishika11 commented
Please ignore the changes in the last 2 commits, I messed a few things and was only removing the changes that happened because of it

2020-07-11 15:46 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/style_index.css
> +}
newline

2020-07-11 15:46 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/style_my_book.css
> +}
newline

2020-07-11 15:50 UTC, abhatia2107 approved these changes
Please add newline to end of every file before submitting. Otherwise it looks good, great work 👍

2020-07-11 19:03 UTC, abhatia2107 requested changes

2020-07-11 19:03 UTC, abhatia2107 commented on walkthroughs/week-1-web-development/examples/stanley/src/main/webapp/mybook.html
> +      <h1 style="color: Orange;">Helix - Ishika Kumar</h1>
Remove inline styling.

2020-07-11 19:06 UTC, abhatia2107 approved these changes

2020-07-11 19:24 UTC, merged