Ishika server
Ishika11/SoftwareProductSprint_portfolio pull request #5
Opened 2020-07-10 13:42 UTC by Ishika11

2020-07-11 19:21 UTC, abhatia2107 requested changes

2020-07-11 19:21 UTC, abhatia2107 commented on README.md
> +This is the Server Branch
Eventually both client and server would go in same branch i.e. master. Hence, README.md should be consistent in both. Create a README.md which can work for all of your code.

2020-07-11 19:21 UTC, abhatia2107 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> -  @Override
Why did you remove @Override?

2020-07-11 19:21 UTC, abhatia2107 commented on walkthroughs/week-2-server/examples/random-quotes/src/main/webapp/style.css
> +<br>
newline

2020-07-11 19:21 UTC, abhatia2107 commented on walkthroughs/week-2-server/examples/TextProcessorServlet.java
> +  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
Add @Override

2020-07-12 10:05 UTC, abhatia2107 approved these changes

2020-07-12 12:00 UTC, merged

2020-07-12 12:01 UTC, Ishika11 commented
Merged PP